version: "3.9"

services:
  node_app:
    container_name: node_app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PG_DB=rmd
      - PG_USER=postgres
      - PG_PASSWORD=Password1234
      - PG_HOST=node_db
    depends_on:
      - node_db
    working_dir: /usr/src/app # Set the working directory inside the container
    volumes:
      - ./:/usr/src/app # Mount the app directory on the host to the container
    ports:
      - "3000:3000" # Map port 3000 from the container to port 3000 on the host
    command: npm start # Specify the command to run your Node.js app

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rmd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password1234
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}